runtime: nodejs16 # or another supported version

instance_class: F1

service: default

env_variables:
  GCS_BUCKET: ${GCS_BUCKET}
  PROJECT_ID: ${PROJECT_ID}
  LOCATION: ${LOCATION}
  PRODUCTSET_ID: ${PRODUCTSET_ID}

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
